In [2]:
import cvxpy as cvx
import numpy as np

In [ ]:
#Exercise 1: Generator Production and Storage

# variables de decisión
x = cvx.Variable((4,1), nonneg = True) # Matriz de variables de 4 filas (generadores por mes) y restricción de no negatividad
# Definir los coeficientes de costos una sublista por cada columna
c_x = [[354,183,138,385]]

a = cvx.Variable((4,1), nonneg = True) # Matriz de variables de 4 filas (almacenados cada mes) y restricción de no negatividad
# Definir los coeficientes de costos una sublista por cada columna
c_a = [[2,2,2,2]] # cuesta 5 alamacenar un generador durante un mes

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c_x,x)) + cvx.sum(cvx.multiply(c_a,a))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor
                                                                              # Queremos minimizar los costos totales (producción + almacenamiento)

# Restricciones
r = [
     # Restricciones de oferta
     x[0] <= 25, # número máximo de generadores en agosto es 22
     x[1] <= 21, # número máximo de generadores en septiembre es 36
     x[2] <= 22, # número máximo de generadores en octubre es 38
     x[3] <= 38, # número máximo de generadores en noviembre es 21

     # restricciones de demanda
     x[0] - a[0] >= 10, # Se requieren 10 generadores para agosto, que es lo que se produce en agosto menos lo que se almacenó
     x[1] + a[0] - a[1] >= 15, # Se requieren 15 generadores para sep, que es lo que se produce en sep + lo del mes anterior - lo que se almacenó
     x[2] + a[1] - a[2] >= 25,
     x[3] + a[2] - a[3] >= 20
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,1))
print(np.around(x.value,1)) # ¿Cuántos generadores se producen en ese mes?
print(np.around(a.value,1)) # ¿Cuántos generadores se almacenan en ese mes?


optimal
costo =  16607.0
[[25.]
 [21.]
 [22.]
 [ 2.]]
[[15.]
 [21.]
 [18.]
 [ 0.]]


In [ ]:
#Exercise 2: Car Transportation Optimization

# variables de decisión
x = cvx.Variable((3,2), nonneg = True) # Matriz de variables de 3 filas (origenes) y 2 columnas (destinos), y restricción de no negatividad

# Definir los coeficientes de costos una sublista por cada columna, según la profe tiene dimensiones 3*4
c = [[75,100,102], # km, y vale 1 pseo cada km, a Denver
    [215,108,50]] # A Miami

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor

# Restricciones
r = [
     # Restricciones de oferta
     cvx.sum(x[0,:]) <= 1000, # La capacidad trimestral de autos en los ángeles es 1000
     cvx.sum(x[1,:]) <= 1500, # Capacidad de prod autos Detroit
     cvx.sum(x[2,:]) <= 1200, # Capacidad de prod autos Nueva Orléans

      # restricciones de demanda
     cvx.sum(x[:,0]) >= 2300, # La demandaa trimestral de autos en Denver es de 2300
     cvx.sum(x[:,1]) >= 1400, # demanda trim de autos en Miami

    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("kilometros = ", np.round(P.value,1))
print(np.around(x.value,1))

optimal
kilometros =  286600.0
[[1000.    0.]
 [1300.  200.]
 [   0. 1200.]]


In [3]:
#Exercise 3: Water Distribution Optimization


# variables de decisión
x = cvx.Variable((3,4), nonneg = True) # Matriz de variables de 3 filas (origenes) y 4 columnas (destinos), y restricción de no negatividad
# Lo que debe llevarse desde el río i hasta la ciudad j xij

# Definir los coeficientes de costos una sublista por cada columna, según la profe tiene dimensiones 3*4
c = [[5,3,6],
    [7,6,1],
    [7,6,2],
    [3,1,4]]

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor

# Restricciones, en este caso Oferta>Demanda
r = [
     # Restricciones de oferta
     cvx.sum(x[0,:]) <= 50, # Del río Colombo tenemos 50 m^3 disponibles
     cvx.sum(x[1,:]) <= 60, # Del río Piave tenemos 60 m^3 disponibles
     cvx.sum(x[2,:]) <= 50, # Del río Calorie tenemos 50 m^3 disponibles

      # restricciones de demanda
     cvx.sum(x[:,0]) >= 30, # La necesidad de la ciudad 1 es de 30 m^3
     cvx.sum(x[:,1]) >= 70, # La necesidad de la ciudad 2 es de 70 m^3
     cvx.sum(x[:,2]) >= 0, # La necesidad de la ciudad 3 es de 0 m^3
     cvx.sum(x[:,3]) >= 10 # La necesidad de la ciudad 4 es de 10 m^3
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,1))
print(np.around(x.value,1))

optimal
costo =  270.0
[[ 0.  0.  0.  0.]
 [30. 20.  0. 10.]
 [ 0. 50.  0.  0.]]


/usr/local/lib/python3.12/dist-packages/cvxpy/expressions/constants/constant.py:52: UserWarning: Initializing a Constant with a nested list is undefined behavior. Consider using a numpy array instead.
  warnings.warn(NESTED_LIST_WARNING)


In [ ]:
# variables de decisión
x = cvx.Variable((4,4), nonneg = True) # Matriz de variables de 4 filas (origenes) y 4 columnas (destinos), y restricción de no negatividad

# Definir los coeficientes de costos una sublista por cada columna, según la profe tiene dimensiones 3*4
c = [[2,5,6,5], # Costos de transporte a montería
    [5,5,1,1], # A bogotá
    [2,7,2,6], # A medellín
    [3,1,4,2]] # A Barranquilla

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor

# Restricciones, en este caso Oferta = Demanda
r = [
     # Restricciones de oferta
     cvx.sum(x[0,:]) <= 80, # La planta ubicada en la ciudad 1 puede producir 80 mil cervezas diarias
     cvx.sum(x[1,:]) <= 30,
     cvx.sum(x[2,:]) <= 60,
     cvx.sum(x[3,:]) <= 45,

      # restricciones de demanda
     cvx.sum(x[:,0]) >= 70, #  El almacén ubicado en montería tiene una necesidad de 70 mil cervezas al día
     cvx.sum(x[:,1]) >= 40,
     cvx.sum(x[:,2]) >= 70,
     cvx.sum(x[:,3]) >= 35
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,1))
print(np.around(x.value,1))

optimal
costo =  360.0
[[70.  0. 10.  0.]
 [ 0.  0.  0. 30.]
 [ 0.  0. 60.  0.]
 [ 0. 40.  0.  5.]]


In [ ]:
# variables de decisión
x = cvx.Variable((3,4), nonneg = True) # Matriz de variables de 3 filas (origenes) y 4 columnas (destinos), y restricción de no negatividad

# Definir los coeficientes de costos una sublista por cada columna, según la profe tiene dimensiones 3*4

#     M1   M2   M3
c = [[866, 547, 707], #C1
    [861, 622, 664],  #C2
    [612, 433, 426],  #C3
    [590, 570, 779]]  #C4

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor

# Restricciones
r = [
     # Restricciones de oferta
     cvx.sum(x[0,:]) <= 75, # La mina 1 puede producir hasta 75 toneladas de carbón (fila 0 = Mina 1)
     cvx.sum(x[1,:]) <= 125, # (fila 1 = mina 2) 125 toneladas de carbón
     cvx.sum(x[2,:]) <= 100, # (fila 2 = mina 3)

      # restricciones de demanda
     cvx.sum(x[:,0]) >= 80, # El centro 1 (columna 1 -> 0) tiene una demanda de 80 toneladas de carbón
     cvx.sum(x[:,1]) >= 65,
     cvx.sum(x[:,2]) >= 70,
     cvx.sum(x[:,3]) >= 85
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,2))
print(np.around(x.value,1))

optimal
costo =  165220.0
[[ 0.  0.  0. 75.]
 [80. 35.  0. 10.]
 [ 0. 30. 70.  0.]]


In [ ]:
# variables de decisión
x = cvx.Variable((4,4), nonneg = True) # Matriz de variables de 4 filas (origenes) y 4 columnas (destinos), y restricción de no negatividad

# Definir los coeficientes de costos una sublista por cada columna, según la profe tiene dimensiones 3*4
c = [[5,3,6,4],
    [2,6,1,3],
    [7,6,2,6],
    [3,1,4,6]]

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor

# Restricciones, en este caso Oferta = Demanda
r = [
     # Restricciones de oferta
     cvx.sum(x[0,:]) <= 80, # en Montería puede producir 80 mil cervezas diarias
     cvx.sum(x[1,:]) <= 30,
     cvx.sum(x[2,:]) <= 60,
     cvx.sum(x[3,:]) <= 45,

      # restricciones de demanda
     cvx.sum(x[:,0]) >= 70, #  El almacén ubicado en montería tiene una necesidad de 70 mil cervezas al día
     cvx.sum(x[:,1]) >= 40,
     cvx.sum(x[:,2]) >= 70,
     cvx.sum(x[:,3]) >= 35,

     # no es posible enviar más de 12 mil cervezas de Montería a Bogotá. -> X12 = X[0,1] (ya está en miles)
     x[0,1] <= 15
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,1))
print(np.around(x.value,1))

optimal
costo =  670.0
[[35.1 15.   6.4 23.5]
 [18.5  0.   0.  11.5]
 [ 0.   0.  60.   0. ]
 [16.4 25.   3.6  0. ]]


In [ ]:
# variables de decisión
x = cvx.Variable((5,5), boolean = True) # decisión de trazar un camino directo entre las veredas ij (i=1..5, j=1..5)

# Función objetivo: Minimizar la longitud de los kilómetros de carretera
no = 99999

a, b, c, d, e, f, g, h, k = 29, 18, 2, 3, 2, 3, 11, 14, 7

#      1   2   3   4   5
c = [[no,  a,  b, no,  c], # 1
     [ a, no,  e,  k,  f], # 2
     [ b,  e, no,  g,  d], # 3
     [no,  k,  g, no,  h], # 4
     [ c,  f,  d,  h, no]] # 5

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) / 2 # Lo dividimos entre dos, pues cuenta el costo de cada camino dos veces (por la restri. de simetría)

# restricciones
r = [
    # de demanda (cada nodo conectado con otro nodo, por lo menos)
    cvx.sum(x[:,0]) >= 1,
    cvx.sum(x[:,1]) >= 1,
    cvx.sum(x[:,2]) >= 1,
    cvx.sum(x[:,3]) >= 1,
    cvx.sum(x[:,4]) >= 1,

    # de simetría
    cvx.upper_tri(x) == cvx.upper_tri(x.T),

    # de redes conectadas
    cvx.sum(x) >= (5-1)*2, # tantos enlaces como (# nodos - 1), y *2 porque se cuentan dos veces
]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
14.0
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


In [ ]:
# variables de decisión xij: cantidad de carros que van del nodo i al nodo j (i=1..7, j=1..7)
x = cvx.Variable((7,7), nonneg = True)

# función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6])) # Maximizamos la cantidad que sale de la ciudad, representandolo como la cantidad que llega al nodo destino

# restricciones

a, b, c, d, e, f, g, h, i, k, m, n, q, s = 29, 18, 2, 3, 2, 3, 11, 14, 7, 5, 2, 2, 8, 14

    # 1  2  3  4  5  6  7
b = [[0, 0, 0, 0, 0, 0, 0], #1
     [a, 0, d, 0, 0, 0, 0], #2
     [b, e, 0, 0, 0, 0, 0], #3
     [c, 0, f, 0, 0, 0, 0], #4
     [0, g, h, 0, 0, m, 0], #5
     [0, 0, i, k, n, 0, 0], #6
     [0, 0, 0, 0, q, s, 0]] #7

r = [
    # de capacidad máxima por tramo xij
    x <= b,

    # carros que entran y que salen
    cvx.sum(x[0,:]) == cvx.sum(x[:,6]),
              #1                #2

     # nodos de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(np.round(P.value,1))
print(np.round(x.value,1))

22.0
[[ 0.   7.6 12.4  2.   0.   0.   0. ]
 [ 0.   0.   1.4  0.   6.9  0.   0. ]
 [ 0.   0.7  0.   3.   3.1  7.   0. ]
 [ 0.   0.   0.   0.   0.   5.   0. ]
 [ 0.   0.   0.   0.   0.   2.   8. ]
 [ 0.   0.   0.   0.   0.   0.  14. ]
 [ 0.   0.   0.   0.   0.   0.   0. ]]


In [ ]:
# variables de decisión
x = cvx.Variable((3,4), nonneg = True) # Matriz de variables de 3 filas (origenes) y 4 columnas (destinos), y restricción de no negatividad

# Definir los coeficientes de costos una sublista por cada columna, según la profe tiene dimensiones 3*4

#     M1   M2   M3
c = [[751, 419, 307], #C1
    [392, 896, 335],  #C2
    [987, 385, 400],  #C3
    [663, 542, 317]]  #C4

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor

# Restricciones
r = [
     # Restricciones de oferta
     cvx.sum(x[0,:]) <= 75, # La mina 1 puede producir hasta 75 toneladas de carbón (fila 0 = Mina 1)
     cvx.sum(x[1,:]) <= 125, # (fila 1 = mina 2) 125 toneladas de carbón
     cvx.sum(x[2,:]) <= 100, # (fila 2 = mina 3)

      # restricciones de demanda
     cvx.sum(x[:,0]) >= 80, # El centro 1 (columna 1 -> 0) tiene una demanda de 80 toneladas de carbón
     cvx.sum(x[:,1]) >= 65,
     cvx.sum(x[:,2]) >= 70,
     cvx.sum(x[:,3]) >= 85
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,2))
print(np.around(x.value,1))

optimal
costo =  113555.0
[[ 0. 65.  0. 10.]
 [55.  0. 70.  0.]
 [25.  0.  0. 75.]]


In [ ]:
# variables de decisión
x = cvx.Variable((4,1), nonneg = True) # Matriz de variables de 4 filas (generadores por mes) y restricción de no negatividad
# Definir los coeficientes de costos una sublista por cada columna
c_x = [[398,117,443,454]]

a = cvx.Variable((4,1), nonneg = True) # Matriz de variables de 4 filas (almacenados cada mes) y restricción de no negatividad
# Definir los coeficientes de costos una sublista por cada columna
c_a = [[1,1,1,1]] # cuesta 5 alamacenar un generador durante un mes

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c_x,x)) + cvx.sum(cvx.multiply(c_a,a))) # Así multiplica "Componente a componente", y luego se hace la suma de cada valor
                                                                              # Queremos minimizar los costos totales (producción + almacenamiento)

# Restricciones
r = [
     # Restricciones de oferta
     x[0] <= 34, # número máximo de generadores en agosto es 22
     x[1] <= 23, # número máximo de generadores en septiembre es 36
     x[2] <= 20, # número máximo de generadores en octubre es 38
     x[3] <= 22, # número máximo de generadores en noviembre es 21

     # restricciones de demanda
     x[0] - a[0] >= 10, # Se requieren 10 generadores para agosto, que es lo que se produce en agosto menos lo que se almacenó
     x[1] + a[0] - a[1] >= 15, # Se requieren 15 generadores para sep, que es lo que se produce en sep + lo del mes anterior - lo que se almacenó
     x[2] + a[1] - a[2] >= 25,
     x[3] + a[2] - a[3] >= 20
    ]

# Configuración del problema, le pasamos la función objetivo y la lista con las restricciones
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Imprimir resultados
print(P.status)
print("costo = ", np.round(P.value,1))
print(np.around(x.value,1)) # ¿Cuántos generadores se producen en ese mes?
print(np.around(a.value,1)) # ¿Cuántos generadores se almacenan en ese mes?

optimal
costo =  22058.0
[[34.]
 [23.]
 [13.]
 [ 0.]]
[[24.]
 [32.]
 [20.]
 [ 0.]]


In [ ]:
# variables de decisión
x = cvx.Variable((13,13), boolean = True) # xij: Hacer el camino de i a j

# Función objetivo: Lo máximo que me voy a demorar en llegar desde el nodo 1 al 13
no = -99999 # pq queremos maximizar y que no tome los valores dados con no, entonces no colocará los números pequeñitos

a, b, c, d, e, f, g, h, i, k, m, n, p, q, s, v = 8, 2, 1, 2, 10, 1, 2, 2, 6, 4, 1, 1, 1, 6, 10, 8

#     1   2   3   4   5   6   7   8   9  10  11  12  13
c =[[no, no, no, no, no, no, no, no, no, no, no, no, no], # 1
    [ a, no, no, no, no, no, no, no, no, no, no, no, no], # 2
    [no,  b, no, no, no, no, no, no, no, no, no, no, no], # 3
    [no, no,  c, no, no, no, no, no, no, no, no, no, no], # 4
    [no, no, no,  d, no, no, no, no, no, no, no, no, no], # 5
    [no, no, no,  e, no, no, no, no, no, no, no, no, no], # 6
    [no, no, no,  h,  g, no, no, no, no, no, no, no, no], # 7
    [no, no, no, no,  i,  f, no, no, no, no, no, no, no], # 8
    [no, no, no, no, no, no,  n, no, no, no, no, no, no], # 9
    [no, no, no, no, no, no, no,  k, no, no, no, no, no], # 10
    [no, no, no, no, no, no, no, no,  p, no, no, no, no], # 11
    [no, no, no, no, no, no, no, no,  q, no,  s, no, no], # 12
    [no, no, no, no, no, no, no, no, no,  m, no,  v, no]] # 13

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# restricciones
r = [
    # de oferta, el proyecto tiene que iniciar
    cvx.sum(x[0,:]) <= 1 ,

    # de demanda, el proyecto debe terminar, llegar a 13
    cvx.sum(x[:,12]) >=1 ,

    # demás nodos son de transbordo, (lo que llega al nodo k es igual a lo que sale del nodo k), k = 2, 3…12

    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

# Configuración del problema
P = cvx.Problem(Z,r)

P.solve() # slnar el problema

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
35.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
