<a href="https://colab.research.google.com/github/EstebanAgudeloR/Linear-programming-exercises/blob/main/linear_optimization_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install cvxpy
import cvxpy as cvx
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
## Exercise 1: Max Flow in 8-Node Transportation Network



# variables de decisión xij: cantidad de carros que van del nodo i al nodo j (i=1..7, j=1..7)
x = cvx.Variable((8,8), nonneg = True)

# función objetivo TENER CUIDADO CON VERIFICAR QUE SÍ ESTAMOS TRABAJANDO SOBRE EL NODO DE DESTINO
Z = cvx.Maximize(cvx.sum(x[:,7])) # Maximizamos la cantidad que sale de la ciudad, representandolo como la cantidad que llega al nodo destino

# restricciones

    #  I0  I1  I2  I3  I4  I5  I6  I7        #Flujo máximo que puede salir de la columna j a la fila i
b = [[ 0,  0,  0,  0,  0,  0,  0,  0], #I0
     [ 7,  0,  0,  0,  0,  0,  0,  0], #I1
     [25,  0,  0,  0,  0,  0,  0,  0], #I2
     [5,  0,  0,  0,  0,  0,  0,  0], #I3
     [ 0, 10, 20,  0,  0,  0,  0,  0], #I4
     [ 0,  0,  9,  4,  0,  0,  0,  0], #I5
     [ 0,  0,  0, 15,  0,  0,  0,  0], #I6
     [ 0,  0,  0,  0, 18, 40,  9,  0]] #I7


r = [
    # de capacidad máxima por tramo xij
    x <= b,

    # carros que entra debe ser igual a la que sale
    cvx.sum(x[0,:]) == cvx.sum(x[:,7]),

     # nodos de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0

]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(np.round(P.value,1))
print(np.round(x.value,1))

32.0
[[ 0.   5.6 21.4  5.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   5.6  0.   0.   0. ]
 [ 0.   0.   0.   0.  12.4  9.   0.   0. ]
 [ 0.   0.   0.   0.   0.   1.7  3.3  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  18. ]
 [ 0.   0.   0.   0.   0.   0.   0.  10.7]
 [ 0.   0.   0.   0.   0.   0.   0.   3.3]
 [ 0.   0.   0.   0.   0.   0.   0.   0. ]]


In [ ]:
## Exercise 2: Max Flow in 7-Node Transportation Network (Example 1)

# variables de decisión xij: cantidad de carros que van del nodo i al nodo j (i=1..7, j=1..7)
x = cvx.Variable((7,7), nonneg = True)

# función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6])) # Maximizamos la cantidad que sale de la ciudad, representandolo como la cantidad que llega al nodo destino

# restricciones

a, b, c, d, e, f, g, h, i, k, m, n, q, s = 23, 18, 4, 8, 8, 3, 18, 3, 15, 15, 9, 8, 8, 15

    # 1  2  3  4  5  6  7
b = [[0, 0, 0, 0, 0, 0, 0], #1
     [a, 0, d, 0, 0, 0, 0], #2
     [b, e, 0, 0, 0, 0, 0], #3
     [c, 0, f, 0, 0, 0, 0], #4
     [0, g, h, 0, 0, m, 0], #5
     [0, 0, i, k, n, 0, 0], #6
     [0, 0, 0, 0, q, s, 0]] #7

r = [
    # de capacidad máxima por tramo xij
    x <= b,

    # carros que entran y que salen
    cvx.sum(x[0,:]) == cvx.sum(x[:,6]),
              #1                #2

     # nodos de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(np.round(P.value,1))
print(np.round(x.value,1))

In [ ]:
## Exercise 3: Max Flow in 7-Node Transportation Network (Example 2)


# variables de decisión xij: cantidad de carros que van del nodo i al nodo j
x = cvx.Variable((7,7), nonneg = True)

# función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6])) # Maximizamos la cantidad que sale de la ciudad, representandolo como la cantidad que llega al nodo destino

# restricciones
a, b = 6, 3

    #  0   1   2   3   4   5   6         #Flujo máximo que puede salir de la columna j a la fila i
b = [[ 0,  0,  0,  0,  0,  0,  0], #0
     [10,  0,  1,  0,  0,  0,  0], #1
     [10,  1,  0,  0,  4,  0,  0], #2
     [ 0,  8,  0,  0,  3,  0,  0], #3
     [ 0,  a,  4,  3,  0,  2,  0], #4
     [ 0,  0, 12,  0,  2,  0,  0], #5
     [ 0,  0,  0,  7,  2,  b,  0]] #6

r = [
    # de capacidad máxima por tramo xij
    x <= b,

    # lo que entra debe ser igual a lo que sale
    cvx.sum(x[0,:]) == cvx.sum(x[:,6]),

     # nodos de transbordo, lo que sale menos lo que entra debe ser igual a 0, no pueden quedarse con nada
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(np.round(P.value,0))
print(np.round(x.value,1))

12.0
[[0.  7.2 4.8 0.  0.  0.  0. ]
 [0.  0.  0.4 5.6 1.9 0.  0. ]
 [0.  0.6 0.  0.  2.4 3.7 0. ]
 [0.  0.  0.  0.  0.8 0.  7. ]
 [0.  0.  1.6 2.2 0.  0.6 2. ]
 [0.  0.  0.  0.  1.4 0.  3. ]
 [0.  0.  0.  0.  0.  0.  0. ]]


In [ ]:
# variables de decisión xij: cantidad de carros que van del nodo i al nodo j
x = cvx.Variable((11,11), nonneg = True)

# función objetivo
Z = cvx.Maximize(cvx.sum(x[:,10])) # Maximizamos la cantidad que sale de la ciudad, representandolo como la cantidad que llega al nodo destino

# restricciones
a, b = 2, 4

     # O   A   B   C   D   E   F   G   H   I   T
b = [[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0 , 0], # O  # costo de ir del nodo i al nodo j
     [ 4,  0,  0,  0,  0,  0,  0,  0,  0,  0 , 0], # A
     [ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0 , 0], # B
     [ 6,  5,  4,  0,  0,  0,  0,  0,  0,  0 , 0], # C
     [ 0,  3,  0,  2,  0,  0,  0,  0,  0,  0 , 0], # D
     [ 0,  0,  6,  5,  0,  0,  0,  0,  0,  0 , 0], # E
     [ 0,  0,  0,  2,  2,  a,  0,  0,  0,  0 , 0], # F
     [ 0,  0,  0,  0,  b,  0,  2,  0,  2,  0 , 0], # G
     [ 0,  0,  0,  0,  0,  2,  5,  0,  0,  0 , 0], # H
     [ 0,  0,  0,  0,  0,  5,  0,  0,  3,  0 , 0], # I
     [ 0,  0,  0,  0,  0,  0,  0,  7,  8,  4 , 0]] # T

r = [
    # de capacidad máxima por tramo xij
    x <= b,

    # lo que entra debe ser igual a lo que sale
    cvx.sum(x[0,:]) == cvx.sum(x[:,10]),

     # nodos de transbordo, lo que sale menos lo que entra debe ser igual a 0, no pueden quedarse con nada
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0
]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(np.round(P.value,1))
print(np.round(x.value,1))

13.0
[[0.  4.  3.  6.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.3 2.7 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.6 0.  2.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.8 4.3 1.8 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.3 3.2 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.7 0.  1.8 3.2 0. ]
 [0.  0.  0.  0.  0.  0.  0.  1.1 3.7 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  5. ]
 [0.  0.  0.  0.  0.  0.  0.  0.7 0.  0.3 4.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]


In [ ]:
# variables de decisión xij: cantidad de carros que van del nodo i al nodo j
x = cvx.Variable((7,7), nonneg = True)

# función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6])) # Maximizamos la cantidad que sale de la ciudad, representandolo como la cantidad que llega al nodo destino

# restricciones
a, b= 3, 9

    # AI B  C  D  E  F  GT
b = [[0, 0, 0, 0, 0, 0, 0], #AI
     [6, 0, 0, 0, 0, 0, 0], #B
     [4, 0, 0, 0, 0, 0, 0], #C
     [a, 0, 3, 0, 0, 0, 0], #D
     [0, 4, 1, 0, 0, 0, 0], #E
     [0, 0, 3, 4, 0, 0, 0], #F
     [0, 0, 0, 0, b, 9, 0]] #GT

r = [
    # de capacidad máxima por tramo xij
    x <= b,

    # Agua que entra debe ser igual a la que sale
    cvx.sum(x[0,:]) == cvx.sum(x[:,6]),
            #AI - 1           # GT - 7
     # nodos de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

]

# Configuración del problema
P = cvx.Problem(Z,r)

# Solucion el problema
P.solve()

print(np.round(P.value,1))
print(np.round(x.value,1))

11.0
[[0.  4.  4.  3.  0.  0.  0. ]
 [0.  0.  0.  0.  4.  0.  0. ]
 [0.  0.  0.  0.7 0.8 2.5 0. ]
 [0.  0.  0.  0.  0.  3.7 0. ]
 [0.  0.  0.  0.  0.  0.  4.8]
 [0.  0.  0.  0.  0.  0.  6.2]
 [0.  0.  0.  0.  0.  0.  0. ]]


In [ ]:
# variables de decisión
x = cvx.Variable((13,13), boolean = True) # xij: Hacer el camino de i a j

# Función objetivo: Lo máximo que me voy a demorar en llegar desde el nodo 1 al 13
no = 99999 # pq queremos maximizar y que no tome los valores dados con no, entonces no colocará los números pequeñitos

#     1   2   3   4   5   6   7   8   9  10  11  12  13
c =[[no, no, no, no, no, no, no, no, no, no, no, no, no], # 1
    [ 8, no, no, no, no, no, no, no, no, no, no, no, no], # 2
    [no,  2, no, no, no, no, no, no, no, no, no, no, no], # 3
    [no, no, 1, no, no, no, no, no, no, no, no, no, no], # 4
    [no, no, no,  2, no, no, no, no, no, no, no, no, no], # 5
    [no, no, no,  10, no, no, no, no, no, no, no, no, no], # 6
    [no, no, no,  2,  2, no, no, no, no, no, no, no, no], # 7
    [no, no, no, no,  6,  1, no, no, no, no, no, no, no], # 8
    [no, no, no, no, no, no,  1, no, no, no, no, no, no], # 9
    [no, no, no, no, no, no, no,  4, no, no, no, no, no], # 10
    [no, no, no, no, no, no, no, no,  1, no, no, no, no], # 11
    [no, no, no, no, no, no, no, no,  6, no,  10, no, no], # 12
    [no, no, no, no, no, no, no, no, no,  1, no,  8, no]] # 13

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# restricciones
r = [
    # de oferta, el proyecto tiene que iniciar
    cvx.sum(x[0,:]) <= 1 ,

    # de demanda, el proyecto debe terminar, llegar a 13
    cvx.sum(x[:,12]) >=1 ,

    # demás nodos son de transbordo, (lo que llega al nodo k es igual a lo que sale del nodo k), k = 2, 3…12

    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

# Configuración del problema
P = cvx.Problem(Z,r)

P.solve() # slnar el problema

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
24.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# variables de decisión
x = cvx.Variable((13,13), boolean = True) # xij: Hacer el camino de i a j

# Función objetivo: Lo máximo que me voy a demorar en llegar desde el nodo 1 al 13
no = -99999 # pq queremos maximizar y que no tome los valores dados con no, entonces no colocará los números pequeñitos

#     1   2   3   4   5   6   7   8   9  10  11  12  13
c =[[no, no, no, no, no, no, no, no, no, no, no, no, no], # 1
    [ 2, no, no, no, no, no, no, no, no, no, no, no, no], # 2
    [no,  1, no, no, no, no, no, no, no, no, no, no, no], # 3
    [no, no, 6, no, no, no, no, no, no, no, no, no, no], # 4
    [no, no, no,  3, no, no, no, no, no, no, no, no, no], # 5
    [no, no, no,  8, no, no, no, no, no, no, no, no, no], # 6
    [no, no, no,  1,  3, no, no, no, no, no, no, no, no], # 7
    [no, no, no, no,  2,  7, no, no, no, no, no, no, no], # 8
    [no, no, no, no, no, no,  3, no, no, no, no, no, no], # 9
    [no, no, no, no, no, no, no,  10, no, no, no, no, no], # 10
    [no, no, no, no, no, no, no, no,  2, no, no, no, no], # 11
    [no, no, no, no, no, no, no, no,  9, no,  4, no, no], # 12
    [no, no, no, no, no, no, no, no, no,  8, no,  3, no]] # 13

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# restricciones
r = [
    # de oferta, el proyecto tiene que iniciar
    cvx.sum(x[0,:]) <= 1 ,

    # de demanda, el proyecto debe terminar, llegar a 13
    cvx.sum(x[:,12]) >=1 ,

    # demás nodos son de transbordo, (lo que llega al nodo k es igual a lo que sale del nodo k), k = 2, 3…12

    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

# Configuración del problema
P = cvx.Problem(Z,r)

P.solve() # slnar el problema

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
42.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# variables de decisión
x = cvx.Variable((8,8), boolean = True) # xij: Hacer el camino de i a j

# Función objetivo: Lo máximo que me voy a demorar en llegar desde el nodo 1 al 13
no = -99999 # pq queremos maximizar y que no tome los valores dados con no, entonces no colocará los números pequeñitos

A, B, C, D, E, F, G, H = 30, 6, 4, 5, 10, 15, 14, 2

#     0   1   2   3   4   5   6   7
c =[[no, no, no, no, no, no, no, no], # 0
    [ A, no, no, no, no, no, no, no], # 1
    [no,  B, no, no,  0, no, no, no], # 2
    [no,  D, no, no, no, no, no, no], # 3
    [no,  G, no, no, no, no, no, no], # 4
    [no, no, no,  E,  0, no, no, no], # 5
    [no, no,  C, no, no,  F, no, no], # 6
    [no, no, no, no, no, no,  H, no]] # 7


Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# restricciones
r = [
    # de oferta, el proyecto tiene que iniciar
    cvx.sum(x[0,:]) <= 1 ,

    # de demanda, el proyecto debe terminar, es decir llegar al nodo final
    cvx.sum(x[:,7]) >= 1 ,

    # demás nodos son de transbordo, (lo que llega al nodo k es igual a lo que sale del nodo k), k = 2, 3…12

    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
]

# Configuración del problema
P = cvx.Problem(Z,r)

P.solve() # slnar el problema

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
62.0
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# variables de decisión
x = cvx.Variable((8,8), boolean = True) # xij: Hacer el camino de i a j

# Función objetivo: Lo máximo que me voy a demorar en llegar desde el nodo 1 al 13
no = -99999 # pq queremos maximizar y que no tome los valores dados con no, entonces no colocará los números pequeñitos

a, b = 11, 3
A, B, C, D, E, F, G = 4, a, 3, 3, 6, 5, b

#     0   1   2   3   4   5   6   7
c =[[no, no, no, no, no, no, no, no], # 0
    [ A, no, no, no, no, no, no, no], # 1
    [ B,  D, no, no, no, no, no, no], # 2
    [ C, no, no, no, no, no, no, no], # 3
    [no,  E, no, no, no, no, no, no], # 4
    [no, no, no,  F, no, no, no, no], # 5
    [no, no,  G, no, no, no, no, no], # 6
    [no, no, no, no,  0,  0,  0, no]] # 7

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# restricciones
r = [
    # de oferta, el proyecto tiene que iniciar
    cvx.sum(x[0,:]) <= 1 ,

    # de demanda, el proyecto debe terminar, es decir llegar al nodo final
    cvx.sum(x[:,7]) >= 1 ,

    # demás nodos son de transbordo, (lo que llega al nodo k es igual a lo que sale del nodo k), k = 2, 3…12

    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
]

# Configuración del problema
P = cvx.Problem(Z,r)

P.solve() # slnar el problema

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
14.0
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# variables de decisión
x = cvx.Variable((13,13), boolean = True) # xij: Hacer el camino de i a j

# Función objetivo: Lo máximo que me voy a demorar en llegar desde el nodo 1 al 13
no = -99999 # pq queremos maximizar y que no tome los valores dados con no, entonces no colocará los números pequeñitos

a, b = 13, 6
A, B, C, D, E, F, G, H, I, J, K, L, M, N = 25, 5, 10, 10, a, 12, 15, 15, 12, 20, 10, b, 25, 10
#     0   1   2   3   4   5   6   7   8   9  10  11  12
c =[[no, no, no, no, no, no, no, no, no, no, no, no, no], # 0
    [ A, no, no, no, no, no, no, no, no, no, no, no, no], # 1
    [no,  B, no, no, no, no, no, no, no, no, no, no, no], # 2
    [no,  C, no, no, no, no, no, no, no, no, no, no, no], # 3
    [no, no,  F, no, no, no, no, no, no, no, no, no, no], # 4
    [no, no, no,  E, no, no, no, no, no, no, no, no, no], # 5
    [no, no, no, no,  I, no, no,  H, no, no, no, no, no], # 6
    [no, no, no, no, no,  G, no, no, no, no, no, no, no], # 7
    [no, no,  D, no, no, no,  J, no, no, no, no, no, no], # 8
    [no, no, no, no, no, no, no, no,  K, no, no, no, no], # 9
    [no, no, no, no, no, no, no, no, no,  L, no, no, no], # 10
    [no, no, no, no, no, no, no, no, no, no,  M, no, no], # 11
    [no, no, no, no, no, no, no, no, no, no, no, N, no]] # 12

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# restricciones
r = [
    # de oferta, el proyecto tiene que iniciar
    cvx.sum(x[0,:]) <= 1 ,

    # de demanda, el proyecto debe terminar, llegar a 13
    cvx.sum(x[:,12]) >=1 ,

    # demás nodos son de transbordo, (lo que llega al nodo k es igual a lo que sale del nodo k), k = 2, 3…12

    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

# Configuración del problema
P = cvx.Problem(Z,r)

P.solve() # slnar el problema

print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
149.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
